services:
  backend:
    build: backend
    networks:
     - t_network
    environment:
      MYSQL_HOST: database
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'pass'
      MYSQL_DB: 'mysql'
    links:
      - database
    depends_on:
      - database
  nginx:
    image: nginx
    volumes:
     - ./nginx:/etc/nginx/conf.d/
    depends_on:
     - backend
    ports:
     - '8081:8080'
    networks:
     - t_network
  database:
    image: mysql
    container_name: 'database'
    volumes:
       - "./database:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_ROOT_PASSWORD: 'pass'
      
    ports:
      - '3307:3306'
    networks:
      - t_network
networks:
  t_network:
    driver: bridge
